import 'package:voccent/generated/l10n.dart';

extension StringCasingExtension on String {
  String toCapitalized() =>
      isNotEmpty ? '${this[0].toUpperCase()}${substring(1).toLowerCase()}' : '';
}

String translateCategory(String name) {
// Remove non-alphanumeric chars and capitalize.
// If translation not found, return original category name
  final curedName =
      name.split(RegExp(r'[^\w\d]')).map((word) => word.toCapitalized()).join();
  return categoriesTranslation['category$curedName'] ?? name;
}

final Map<String, String> categoriesTranslation = {
  'category4Seasons': S.current.category4Seasons,
  'category5Senses': S.current.category5Senses,
  'categoryAddress': S.current.categoryAddress,
  'categoryAgileMethodology': S.current.categoryAgileMethodology,
  'categoryAirport': S.current.categoryAirport,
  'categoryAlphabet': S.current.categoryAlphabet,
  'categoryAnimals': S.current.categoryAnimals,
  'categoryAllCategories': S.current.categoryAllCategories,
  'categoryAppointments': S.current.categoryAppointments,
  'categoryAquaticSemiAquaticAnimals':
      S.current.categoryAquaticSemiAquaticAnimals,
  'categoryBasics': S.current.categoryBasics,
  'categoryBeingPolite': S.current.categoryBeingPolite,
  'categoryBody': S.current.categoryBody,
  'categoryBodyParts': S.current.categoryBodyParts,
  'categoryBusiness': S.current.categoryBusiness,
  'categoryCelebrations': S.current.categoryCelebrations,
  'categoryClothing': S.current.categoryClothing,
  'categoryCommunity': S.current.categoryCommunity,
  'categoryCommunityHelpers': S.current.categoryCommunityHelpers,
  'categoryConflict': S.current.categoryConflict,
  'categoryCooking': S.current.categoryCooking,
  'categoryCountriesContinents': S.current.categoryCountriesContinents,
  'categoryCulture': S.current.categoryCulture,
  'categoryDaysMonthsYears': S.current.categoryDaysMonthsYears,
  'categoryDirections': S.current.categoryDirections,
  'categoryDomesticAnimalsPets': S.current.categoryDomesticAnimalsPets,
  'categoryEmails': S.current.categoryEmails,
  'categoryEnvironmentalIssues': S.current.categoryEnvironmentalIssues,
  'categoryExtendedFamily': S.current.categoryExtendedFamily,
  'categoryFamily': S.current.categoryFamily,
  'categoryFeelingsEmotions': S.current.categoryFeelingsEmotions,
  'categoryFood': S.current.categoryFood,
  'categoryGovernment': S.current.categoryGovernment,
  'categoryGrammar': S.current.categoryGrammar,
  'categoryGreetings': S.current.categoryGreetings,
  'categoryHealth': S.current.categoryHealth,
  'categoryHolidayGreetings': S.current.categoryHolidayGreetings,
  'categoryHolidays': S.current.categoryHolidays,
  'categoryImmediateFamily': S.current.categoryImmediateFamily,
  'categoryImmigration': S.current.categoryImmigration,
  'categoryIndoorOutdoorActivates': S.current.categoryIndoorOutdoorActivates,
  'categoryInformationTechnology': S.current.categoryInformationTechnology,
  'categoryInternationalDomesticTravel':
      S.current.categoryInternationalDomesticTravel,
  'categoryInterviewing': S.current.categoryInterviewing,
  'categoryIntroductions': S.current.categoryIntroductions,
  'categoryJobDescriptions': S.current.categoryJobDescriptions,
  'categoryLandmarks': S.current.categoryLandmarks,
  'categoryLanguageTesting': S.current.categoryLanguageTesting,
  'categoryLeadingMeetings': S.current.categoryLeadingMeetings,
  'categoryLife': S.current.categoryLife,
  'categoryLifeAbroad': S.current.categoryLifeAbroad,
  'categoryMathTerms': S.current.categoryMathTerms,
  'categoryMathematics': S.current.categoryMathematics,
  'categoryMeals': S.current.categoryMeals,
  'categoryMeetingNewPeople': S.current.categoryMeetingNewPeople,
  'categoryMentalHealth': S.current.categoryMentalHealth,
  'categoryMoneyAndFinances': S.current.categoryMoneyAndFinances,
  'categoryMovements': S.current.categoryMovements,
  'categoryNegotiations': S.current.categoryNegotiations,
  'categoryNeighborhood': S.current.categoryNeighborhood,
  'categoryNumbers': S.current.categoryNumbers,
  'categoryOrderingOut': S.current.categoryOrderingOut,
  'categoryOurWorld': S.current.categoryOurWorld,
  'categoryPastPresentFuture': S.current.categoryPastPresentFuture,
  'categoryPhoneNumber': S.current.categoryPhoneNumber,
  'categoryPhonetics': S.current.categoryPhonetics,
  'categoryPhonics': S.current.categoryPhonics,
  'categoryPhrases': S.current.categoryPhrases,
  'categoryPollution': S.current.categoryPollution,
  'categoryProfessionalRoles': S.current.categoryProfessionalRoles,
  'categoryPublicTransportation': S.current.categoryPublicTransportation,
  'categoryReligion': S.current.categoryReligion,
  'categoryRestaurants': S.current.categoryRestaurants,
  'categorySafety': S.current.categorySafety,
  'categorySchool': S.current.categorySchool,
  'categorySharingInformation': S.current.categorySharingInformation,
  'categoryShopping': S.current.categoryShopping,
  'categorySmallTalk': S.current.categorySmallTalk,
  'categorySportsPlay': S.current.categorySportsPlay,
  'categoryStorytelling': S.current.categoryStorytelling,
  'categorySubjects': S.current.categorySubjects,
  'categoryTechnology': S.current.categoryTechnology,
  'categoryTheWeather': S.current.categoryTheWeather,
  'categoryTime': S.current.categoryTime,
  'categoryTraditions': S.current.categoryTraditions,
  'categoryTravel': S.current.categoryTravel,
  'categoryVehicles': S.current.categoryVehicles,
  'categoryVocabulary': S.current.categoryVocabulary,
  'categoryWildAnimals': S.current.categoryWildAnimals,
  'categoryWork': S.current.categoryWork,
  'categoryWorkingOut': S.current.categoryWorkingOut,
  'categoryYoga': S.current.categoryYoga,
};
