// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQH3NQg8pW3C8UYls8U9zj-HaR4dOfzgw',
    appId: '1:936783312403:web:b97d5b1aa74a0deeadb1e6',
    messagingSenderId: '936783312403',
    projectId: 'voccent',
    authDomain: 'voccent.firebaseapp.com',
    databaseURL: 'https://voccent.firebaseio.com',
    storageBucket: 'voccent.appspot.com',
    measurementId: 'G-H96V4WTQBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkKwJJPORyNngmR6jEWa4sHZnlsHaOmJo',
    appId: '1:936783312403:android:b1aa0f97feffc3b2adb1e6',
    messagingSenderId: '936783312403',
    projectId: 'voccent',
    databaseURL: 'https://voccent.firebaseio.com',
    storageBucket: 'voccent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCkdFfhSIDUytB9nu5Fdx4GFhWcn0sb8',
    appId: '1:936783312403:ios:f8442f3a9a4372c4adb1e6',
    messagingSenderId: '936783312403',
    projectId: 'voccent',
    databaseURL: 'https://voccent.firebaseio.com',
    storageBucket: 'voccent.appspot.com',
    androidClientId:
        '936783312403-19kd4e6pl4bq0p76db6jvnttte2eg7cq.apps.googleusercontent.com',
    iosClientId:
        '936783312403-8jnb9cfn895nlc704j9c14h1ggt818gq.apps.googleusercontent.com',
    iosBundleId: 'com.voccent.learn.stg.iPad',
  );
}
